"""PlatformIO pre-build script: write src/build_info.h with the git state and
build time so the firmware can identify itself on the serial log at boot.

Generated macros (all string literals):
    MK_BUILD_GIT   e.g. "9781d4b" or "9781d4b-dirty"  ("nogit" when unavailable)
    MK_BUILD_TIME  e.g. "2026-09-06 04:10 UTC"
    MK_BUILD_ENV   PlatformIO environment name, e.g. "esp32s3box"

The header is regenerated on every build and is git-ignored. Only the
translation units that include it recompile when it changes.
"""
import datetime
import os
import subprocess

Import("env")  # noqa: F821  (PlatformIO injects this)

project_dir = env["PROJECT_DIR"]  # noqa: F821
out_path = os.path.join(project_dir, "src", "build_info.h")


def git(*args):
    try:
        return subprocess.check_output(
            ["git", *args], cwd=project_dir, stderr=subprocess.DEVNULL, text=True
        ).strip()
    except Exception:
        return ""


sha = git("rev-parse", "--short=7", "HEAD") or "nogit"
if sha != "nogit" and git("status", "--porcelain", "--untracked-files=no"):
    sha += "-dirty"
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
pio_env = env["PIOENV"]  # noqa: F821

content = (
    "/* Generated by tools/gen_build_info.py at build time. Do not edit, do not commit. */\n"
    "#pragma once\n"
    f'#define MK_BUILD_GIT  "{sha}"\n'
    f'#define MK_BUILD_TIME "{now}"\n'
    f'#define MK_BUILD_ENV  "{pio_env}"\n'
)

# Write only when the content changed, so an unchanged tree does not force a
# rebuild of the including units on every run (the time stamp is minute-granular).
previous = ""
if os.path.exists(out_path):
    with open(out_path, "r", encoding="utf-8") as f:
        previous = f.read()
if previous.split("MK_BUILD_TIME")[0] != content.split("MK_BUILD_TIME")[0] or not previous:
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
else:
    # git state unchanged: refresh the time stamp anyway (cheap, one small TU)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

print(f"[build_info] {sha} {now} ({pio_env})")
