#!/usr/bin/env python3
"""Regenerate src/ui/images/ui_img_ac_remote_png.c (the App 11 "AC Remote" icon).

The vendor icons are 70x70 LVGL TRUE_COLOR_ALPHA arrays exported by SquareLine
from PNGs we do not have. This script rebuilds the same look procedurally:

1. Samples the radial colour/alpha profile of an existing icon disc
   (ui_img_smarthome_png.c), keeping only saturated green pixels so the white
   glyph and its anti-aliased edges do not contaminate the gradient.
2. Draws a white split-type indoor unit with a vent slot and a red status LED
   plus three downward airflow arcs, 4x supersampled, then downsamples.
3. Writes the C array in the SquareLine layout (RGB565 little-endian + alpha,
   12 bytes per line) and, with --png, also the PNG next to it for review.

Usage:  python tools/make_ac_remote_icon.py [--png out.png]
Requires Pillow.
"""
import argparse
import math
import re

from PIL import Image, ImageDraw, ImageFilter

TEMPLATE = "src/ui/images/ui_img_smarthome_png.c"
OUTPUT = "src/ui/images/ui_img_ac_remote_png.c"
W = H = 70
CX = CY = 34.5
SS = 4


def decode_c_array(path):
    txt = open(path, encoding="utf-8-sig").read()
    body = txt[txt.index("[] = {") + 6: txt.index("};", txt.index("[] = {"))]
    data = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{2}", body)]
    img = Image.new("RGBA", (W, H))
    px = img.load()
    for i in range(W * H):
        v = data[i * 3] | (data[i * 3 + 1] << 8)
        px[i % W, i // W] = (((v >> 11) & 31) * 255 // 31, ((v >> 5) & 63) * 255 // 63,
                             (v & 31) * 255 // 31, data[i * 3 + 2])
    return img, txt


def disc_profile(img):
    px = img.load()
    prof, aprof = {}, {}
    for y in range(H):
        for x in range(W):
            r, g, b, a = px[x, y]
            rad = int(round(math.hypot(x - CX, y - CY)))
            aprof.setdefault(rad, []).append(a)
            if a < 200 or max(r, g, b) - min(r, g, b) < 70 or g < r or g < b:
                continue
            prof.setdefault(rad, []).append((r, g, b))
    maxr = max(aprof)
    col = [None] * (maxr + 2)
    alp = [0] * (maxr + 2)
    for rad in range(maxr + 2):
        v = prof.get(rad)
        if v and len(v) >= 3:
            col[rad] = tuple(sum(c[i] for c in v) // len(v) for i in range(3))
        av = aprof.get(rad)
        alp[rad] = sum(av) // len(av) if av else 0
    for rad in range(maxr + 2):          # fill radii hidden by the template glyph
        if col[rad] is None:
            k = rad
            while k <= maxr + 1 and col[k] is None:
                k += 1
            col[rad] = col[k] if k <= maxr + 1 else col[rad - 1]
    smooth = []
    for i in range(maxr + 2):
        n = [col[j] for j in (i - 1, i, i + 1) if 0 <= j <= maxr + 1]
        smooth.append(tuple(sum(c[k] for c in n) // len(n) for k in range(3)))
    return smooth, alp, maxr


def draw_icon(col, alp, maxr):
    big = Image.new("RGBA", (W * SS, H * SS), (0, 0, 0, 0))
    bp = big.load()
    for y in range(H * SS):
        for x in range(W * SS):
            rad = math.hypot((x + 0.5) / SS - CX, (y + 0.5) / SS - CY)
            if rad > maxr + 0.5:
                continue
            ri = min(int(round(rad)), maxr + 1)
            bp[x, y] = col[ri] + (alp[ri],)

    def r(*v):
        return [int(round(t * SS)) for t in v]

    def unit(dr, dx=0.0, dy=0.0, fill=(255, 255, 255, 255)):
        dr.rounded_rectangle(r(14 + dx, 15 + dy, 56 + dx, 33 + dy), radius=int(3.5 * SS), fill=fill)

    shadow = Image.new("RGBA", big.size, (0, 0, 0, 0))
    unit(ImageDraw.Draw(shadow), 1.2, 1.4, (0, 0, 0, 120))
    big.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(1.6 * SS)))

    d = ImageDraw.Draw(big)
    unit(d)
    d.rounded_rectangle(r(18, 27.4, 46, 29.6), radius=SS, fill=(96, 160, 20, 255))   # vent slot
    d.ellipse(r(49.2, 26.6, 52.6, 30), fill=(232, 60, 45, 255))                        # status LED
    for i, (yy, wd, al) in enumerate(((37, 2.6, 255), (44, 2.3, 235), (51, 2.0, 210))):
        half = 14 - i * 2.5
        d.arc(r(35 - half, yy, 35 + half, yy + 10), start=20, end=160,
              fill=(255, 255, 255, al), width=int(wd * SS))
    return big.resize((W, H), Image.LANCZOS)


def write_c_array(icon, template_txt):
    px = icon.load()
    data = []
    for y in range(H):
        for x in range(W):
            rr, gg, bb, aa = px[x, y]
            v = ((rr >> 3) << 11) | ((gg >> 2) << 5) | (bb >> 3)
            data += [v & 0xFF, v >> 8, aa]
    head = template_txt[:template_txt.index("const LV_ATTRIBUTE_MEM_ALIGN uint8_t")]
    head = head.replace("assets/smarthome.png",
                        "assets/ac_remote.png (generated by tools/make_ac_remote_icon.py)")
    tail = template_txt[template_txt.index("const lv_img_dsc_t"):].replace(
        "ui_img_smarthome_png", "ui_img_ac_remote_png")
    lines = ["    " + ",".join(f"0x{b:02X}" for b in data[i:i + 12]) + "," for i in range(0, len(data), 12)]
    body = ("const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_ac_remote_png_data[] = {\n"
            + "\n".join(lines) + "\n};\n\n")
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(head + body + tail)
    return len(data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png", help="also save the icon as PNG here")
    args = ap.parse_args()
    template_img, template_txt = decode_c_array(TEMPLATE)
    col, alp, maxr = disc_profile(template_img)
    icon = draw_icon(col, alp, maxr)
    n = write_c_array(icon, template_txt)
    if args.png:
        icon.save(args.png)
    print(f"wrote {OUTPUT} ({n} bytes of pixel data)")


if __name__ == "__main__":
    main()
